language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
script:
  - "npm test"
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run test-saucelabs; fi
env:
  global:
    - secure: GCD8IZsf+apGess3RXaS9oDLOR4iUU2piV0/hIUgcsFtWcDWDBN5dpDPu/ol8T7Hae+Fq7ZnOPCFj3ioBCj4kTneHOvTbq9sMRzUd97U1iY/LlIxggQlF4Q5g3ZZ2LIT7R/FjCf2ntVOXeipHwcZgx/8mVW4B9A5iJL26mhpyPs=
    - secure: RrWtg0n/SoCZXjtvdBxy9+ooowNlCZYI7S35bja4d4o+Tk9kNGmS/l85YD7SE4RfW5+m5Z4U8ct+tYu6Fjbv8FDeOVyOPkOsWVX9fcDzP5n6ylyEvvppf8jKrbORgp3Kg37n0GtaCkhV8FaPgJ2gxjWhJdgatsGtWNz4MkvT5LM=
